# Generated by Django 2.2.16 on 2022-05-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction_services', '0003_errorreport_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseauction',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseauction',
            name='auction_venue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseauction',
            name='domain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseauction',
            name='picture_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseauction',
            name='property_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseauction',
            name='property_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseauction',
            name='tenure',
            field=models.TextField(blank=True, null=True),
        ),
    ]
